# Numpy Ödev 2

1) 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.


In [1]:
import numpy as np

In [3]:
arr = np.arange(0,30)
arr.reshape(15,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

2) 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.


In [8]:
arr2 = np.random.randint(0,50, 60)
arr2 = arr2.reshape(5,3,-1)
print(arr2)
print("Dimension:", arr2.ndim)
print("Shape: ", arr2.shape)

[[[45 36 48 39]
  [ 7 45 22 14]
  [42 45 40 19]]

 [[16 14 47 24]
  [ 6 23 35 46]
  [ 6 35 40 35]]

 [[38 38 12 36]
  [24  6 47 21]
  [ 3 11  5 42]]

 [[14 44 15 11]
  [16  5 22 39]
  [ 3 27  2 13]]

 [[37 16 39 13]
  [ 2  6 33 29]
  [49 11 23 31]]]
Dimension: 3
Shape:  (5, 3, 4)


3) 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.


In [11]:
arr3 = np.random.randint(10,30, size=(5,4))
print(arr3)
arr3 = arr3.reshape(-1)
print("--------- AFTER FLATTEN ----------")
print(arr3)

[[20 15 26 11]
 [21 14 21 13]
 [12 11 13 23]
 [10 23 23 14]
 [25 29 23 29]]
--------- AFTER FLATTEN ----------
[20 15 26 11 21 14 21 13 12 11 13 23 10 23 23 14 25 29 23 29]


4) İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.


In [13]:
arr4 = np.random.randint(10,20, size=(4,4))
arr4

array([[15, 13, 11, 12],
       [13, 14, 18, 12],
       [12, 15, 10, 10],
       [16, 13, 14, 12]])

In [14]:
for i in arr4:
    for j in i:
        print(j)

15
13
11
12
13
14
18
12
12
15
10
10
16
13
14
12


In [16]:
for k in np.nditer(arr4):
    print(k)

15
13
11
12
13
14
18
12
12
15
10
10
16
13
14
12


5) 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve
   1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun.
   Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.

In [3]:
arr5 = np.arange(5,35,5)
arr6 = np.arange(1,7)
print("Toplam:", arr5 + arr6)
print("Fark:", arr5 - arr6)
print("Çarpım:", arr5 * arr6)
print("Bölüm:", arr5 / arr6)

Toplam: [ 6 12 18 24 30 36]
Fark: [ 4  8 12 16 20 24]
Çarpım: [  5  20  45  80 125 180]
Bölüm: [5. 5. 5. 5. 5. 5.]


In [5]:
print("Toplam:", arr5[0] + arr6[0])
print("Fark:", arr5[0] - arr6[0])
print("Çarpım:", arr5[0] * arr6[0])
print("Bölüm:", arr5[0] / arr6[0])

Toplam: 6
Fark: 4
Çarpım: 5
Bölüm: 5.0


6) 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.


In [7]:
arr7 = np.random.randint(0,100, 10)
print("Sum", arr7.sum())
print("Mean", arr7.mean())
print("Max", arr7.max())
print("Min", arr7.min())
print("Var", arr7.var())
print("Std", arr7.std())

Sum 584
Mean 58.4
Max 98
Min 6
Var 806.24
Std 28.394365638274085


7) 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.


In [9]:
arr8 = np.arange(0,21)
arr9 = np.arange(500,531)
arr_con = np.concatenate([arr8, arr9], axis=0)
arr_con

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20, 500, 501, 502, 503, 504,
       505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517,
       518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

8) 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.


In [14]:
arr10 = np.arange(15,51)
arr11 = np.arange(10,101)
arr_con1 = np.concatenate([arr10, arr11])
arr_con1


array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [15]:
arr_con1[25] = 888
arr_con1[50] = 888
arr_con1

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39, 888,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23, 888,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

9) 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.


In [20]:
arr12 = np.random.randint(0,40, (8,5))
arr13 = np.random.randint(320,360, (8,5))
arr_con2 = np.concatenate([arr12, arr13], axis=0)
arr_con3 = np.concatenate([arr12, arr13], axis=1)
print("Axis = 0:", arr_con2)
print("--------------------------")
print("Axis = 1:", arr_con3)

Axis = 0: [[ 13  17  28  17   8]
 [ 22  33  37  20  21]
 [ 27  19   6  27   7]
 [ 14   3  36  21  29]
 [ 25  27  10   7  35]
 [ 10   0  38  23   2]
 [ 14   8  15  39  17]
 [  5   8  32  26  21]
 [350 344 336 332 335]
 [329 349 323 330 346]
 [332 335 322 353 327]
 [347 323 341 339 321]
 [340 337 352 350 347]
 [338 323 344 354 337]
 [329 344 345 341 353]
 [344 341 320 336 355]]
--------------------------
Axis = 1: [[ 13  17  28  17   8 350 344 336 332 335]
 [ 22  33  37  20  21 329 349 323 330 346]
 [ 27  19   6  27   7 332 335 322 353 327]
 [ 14   3  36  21  29 347 323 341 339 321]
 [ 25  27  10   7  35 340 337 352 350 347]
 [ 10   0  38  23   2 338 323 344 354 337]
 [ 14   8  15  39  17 329 344 345 341 353]
 [  5   8  32  26  21 344 341 320 336 355]]


10) 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.

In [21]:
arr_con4 = np.concatenate([arr12, arr13], axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [22]:
arr_con5 = np.stack([arr12, arr13], axis=2)
arr_con5

array([[[ 13, 350],
        [ 17, 344],
        [ 28, 336],
        [ 17, 332],
        [  8, 335]],

       [[ 22, 329],
        [ 33, 349],
        [ 37, 323],
        [ 20, 330],
        [ 21, 346]],

       [[ 27, 332],
        [ 19, 335],
        [  6, 322],
        [ 27, 353],
        [  7, 327]],

       [[ 14, 347],
        [  3, 323],
        [ 36, 341],
        [ 21, 339],
        [ 29, 321]],

       [[ 25, 340],
        [ 27, 337],
        [ 10, 352],
        [  7, 350],
        [ 35, 347]],

       [[ 10, 338],
        [  0, 323],
        [ 38, 344],
        [ 23, 354],
        [  2, 337]],

       [[ 14, 329],
        [  8, 344],
        [ 15, 345],
        [ 39, 341],
        [ 17, 353]],

       [[  5, 344],
        [  8, 341],
        [ 32, 320],
        [ 26, 336],
        [ 21, 355]]])

11) [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.


In [3]:
arr14 = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
np.where(arr14 == 5)

(array([ 5, 13], dtype=int64),)

12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.


In [4]:
np.where(arr14 % 2 == 0)

(array([ 1,  3,  4,  6,  7,  9, 11], dtype=int64),)

13) Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.

In [5]:
np.where(arr14 > 4)


(array([ 1,  2,  5,  9, 10, 11, 13], dtype=int64),)

14) Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.


In [6]:
np.where(arr14 % 5 == 0)


(array([ 1,  2,  5, 13], dtype=int64),)

15) 85-100(100 dahil) arasından rastgele 1 tam sayı seçin

In [40]:
np.random.choice(range(85,101))

87

16) İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.


In [41]:
np.random.randint(low=10, high=99,size=(3,3))

array([[36, 83, 67],
       [63, 49, 80],
       [27, 97, 61]])

17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.


In [42]:
arr15 = np.arange(35, 61)
np.random.choice(arr15)

56

18) Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.

In [44]:
np.random.choice([3, 8, 10, 53], size=(2,5))

array([[ 8,  8, 53,  3,  8],
       [10, 10, 10,  3, 53]])