# Numpy Ödevi

In [2]:
import numpy as np

1) Manuel değerleri el ile girerek 3 boyutlu bir array oluşturup bir değişkene atayın. Ardından 3 boyutlu olup olmadığına bakmak için dimension'ını kontrol edin

In [5]:
arr_1 = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
arr_1

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [6]:
arr_1.ndim

3

2) 34, 40, 46, 52... 112 şeklinde devam eden 1 boyutlu bir array oluşturun.

In [8]:
arr_2 = np.arange(34,113,6)
arr_2

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

In [9]:
arr_2.ndim

1

3) 50-500 arasında lineer artış gösteren 91 tane tam sayıdan oluşan bir array oluşturun.(dtype'ı int olsun)


In [10]:
arr_3 = np.linspace(50, 500, 91, dtype= int)
arr_3

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100, 105, 110,
       115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175,
       180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240,
       245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
       310, 315, 320, 325, 330, 335, 340, 345, 350, 355, 360, 365, 370,
       375, 380, 385, 390, 395, 400, 405, 410, 415, 420, 425, 430, 435,
       440, 445, 450, 455, 460, 465, 470, 475, 480, 485, 490, 495, 500])

4) 100(10^2) ile 10000(10^5) arasında logaritmik artış gösteren 8 sayıdan oluşan bir array oluşturun.


In [13]:
arr_4 = np.logspace(2, 5, 8)
arr_4

array([   100.        ,    268.26957953,    719.685673  ,   1930.69772888,
         5179.47467923,  13894.95494373,  37275.93720315, 100000.        ])

5) 0-8 tam arasındaki ardışık tam sayılardan oluşan(0 ve 8 dahil toplam 9 değer) 3x3 shape'inde bir matris oluşturun.


In [14]:
arr_5 = np.random.randint(0, 8, (3, 3))
arr_5

array([[6, 1, 7],
       [3, 6, 2],
       [2, 6, 3]])

6) 6x6 formatında bir sıfır matrisi oluşturun. (dtype'ı int olsun)


In [16]:
zeros = np.zeros((6,6), dtype= int) # 6x6 sıfır matrisi
zeros

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

7) 4x4 formatında bir bir matrisi oluşturun. (dtype'ı int olsun)


In [18]:
ones = np.ones((4,4), dtype= int) # 4x4 bir matrisi
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

8) 8x8 formatında bir birim matris oluşturun. (Sadece sol köşegeni 1 geri kalan değerleri 0 olan matris'e birim matris deniyor.) (dtype'ı int olsun)
;

In [22]:
eyes= np.eye(8, dtype= 'int') # 8x8 birim matris 
eyes

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

9) 5x5 formatında bir köşegen matrisi oluşturun (Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün değerleri 0) (Bunu henüz görmediniz ama birim matrise benziyor, sadece köşegen değerleri 1 değil 3 olacak. Bir şeyler düşünün)


In [24]:
eyes_1 = np.eye(5, dtype= 'int') * 3
eyes_1

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

10) np.random modülünden uygun fonksiyonu kullanarak 0-1 arasında toplam 6 tane değerden oluşan 1 boyutlu bir array oluşturun.


In [25]:
arr_6 = np.random.rand(6)
arr_6

array([0.64478744, 0.4006173 , 0.77635314, 0.70116131, 0.75096605,
       0.92734657])

11) np.random modülünden uygun fonksiyonu kullanarak 50-100 arasındaki(50 ve 100 dahil) tam sayılardan 10 tanesiyle oluşan (5,2) shape'inde bir array oluşturun. Ardından bu arrayin shape'ini kontrol edin.


In [26]:
arr_7 = np.random.randint(50, 100, (5,2))
arr_7

array([[89, 77],
       [77, 54],
       [82, 71],
       [59, 92],
       [62, 71]])

In [27]:
arr_7.shape

(5, 2)

12) np.random modülünden uygun fonksiyonu kullanarak 100-1000(1000 dahil değil) arasındaki tam sayılardan rastgele 50 tanesinden oluşan (2,5,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in dimension'ını(boyutunu) ve shape'ini kontrol edin.


In [28]:
arr_8 = np.random.randint(100, 1000, size=(2, 5, 5))
print(arr_8)
print(arr_8.ndim)
print(arr_8.shape)

[[[837 261 889 344 357]
  [556 298 350 137 389]
  [397 252 976 914 468]
  [732 252 899 117 194]
  [790 819 164 967 437]]

 [[742 764 982 394 682]
  [855 744 930 993 783]
  [745 431 590 275 188]
  [724 691 169 428 626]
  [254 997 170 658 193]]]
3
(2, 5, 5)


13) np.random modülünden uygun fonksiyonu kullanarak 0-100(0 ve 100 dahil) arasındaki tam sayılardan 10 tane seçerek bir array oluşturun. Bu array'in maximum, mininmum değerlerine ve bu değerlerin indexlerine bakın. 


In [29]:
arr_9 = np.random.randint(0, 101, size=10)
print(arr_9)
print("Max: ", np.max(arr_9))
print("Min: ", np.min(arr_9))
print("Index max: ", np.argmax(arr_9))
print("Index min: ", np.argmin(arr_9))

[88 86 83 50 67 34 74 74 28 54]
Max:  88
Min:  28
Index max:  0
Index min:  8


14) np.random modülünden uygun fonksiyonu kullanarak 300-500(300 ve 500 dahil) arasındaki tam sayılardan 20 tane seçerek (2,2,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in içindeki 20 tam sayı arasından maximum ve minimum değerleri manuel olarak tespit edin ve indexleme yaparak çekmeye çalışın.


In [32]:
arr_10 = np.random.randint(300, 501, size=(2, 2, 5))
print(arr_10)

[[[418 374 324 449 310]
  [403 429 498 313 462]]

 [[465 492 312 428 438]
  [414 333 459 466 479]]]


In [34]:
max_arr_10 = arr_10[0][1][2]
max_arr_10

498

In [35]:
min_arr_10 = arr_10[0][0][4]
min_arr_10

310

15) 0-50(50 dahil) arasındaki ardışık tam sayılardan oluşan bir array oluşturun. Ardından bu arrayin 20. ve 35. indexleri arasındaki değerleri 500'e eşitleyin ve yeni oluşan array'i ekrana yazdırarak broadcasting işleminin yapılıp yapılmadığını test edin.

In [38]:
arr_11 = np.arange(51)
print(arr_11)
arr_11[20:36] = 500
print(arr_11)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50]
